batch_size: 100
dropout: 0.6
epochs: 2
error_buffer: 100
header: [run_id, chan_id, num_anoms, anomaly_sequences, num_values, normalized_error,
  scores]
l_s: 200
layers: [10, 10]
loss_metric: mse
lstm_batch_size: 80
min_delta: 0.03
n_predictions: 1
optimizer: adam
p: 0.0
patience: 10
predict: 'True'
smoothing_perc: 0.04
train: 'True'
use_id: 2019-11-19_23.52.23
validation_split: 0.4
window_size: 5
B: 28
B_2: 28
threshold: -0.3
percentile: 75
